[codex]
version = "0.91.0"

[codex.hashes]
"aarch64-darwin" = "sha256-sWBtHwQ9bIfMkyblnSazE1PNgk0vp+n0ZeTxL69HWxg="
"x86_64-darwin" = "sha256-sSr+bsL/AFiV46szHGfsr9P9D8N00GmL1WmPukK32Xc="
"aarch64-linux" = "sha256-fFs0qQdMreYar1EBSgln1MY5cvpnoRvWhN70YFd9gfg="
"x86_64-linux" = "sha256-xzPdhQbdANDsNvMjCN2QK65D6pNTYv18STPBWvTTxkE="

["claude-code"]
version = "2.1.19"

["claude-code".hashes]
"aarch64-darwin" = "sha256:d386ac8f6d1479f85d31f369421c824135c10249c32087017d05a5f428852c41"
"x86_64-darwin" = "sha256:be266b3a952f483d8358ad141e2afe661170386506f479ead992319e4fdc38ac"
"aarch64-linux" = "sha256:8c4b61b24ca760d6f7aa2f19727163d122e9fd0c3ce91f106a21b6918a7b1bbb"
"x86_64-linux" = "sha256:4e2a1c73871ecf3b133376b57ded03333a7a6387f2d2a3a6279bb90a07f7a944"
