[codex]
version = "0.92.0"

[codex.hashes]
"aarch64-darwin" = "sha256-GgY+04e7Be8LKHWpZBdpcwiXXtZX4BlXi8R410weKIk="
"x86_64-darwin" = "sha256-er78jjbfdDx6z+UkYpPj/S4pWLE3yXdvl2rtjjqRyek="
"aarch64-linux" = "sha256-t0KmxTSskrqcqE3BXg6j67wL3O0FkeO1a1p3yzHWFnU="
"x86_64-linux" = "sha256-dXwAwjxp1hqONy2aBSZrug1hBwWK2JAt2Bi3h/SCWzE="

["claude-code"]
version = "2.1.25"

["claude-code".hashes]
"aarch64-darwin" = "sha256-ECPAM0sL+ZznpGatvbJO0Mrgzk4ROINyOOEys4ht14k="
"x86_64-darwin" = "sha256-E/xfkrb+yEtnSsfPUGUkMj8BLPmZdAcz9zd/b7Rrz9c="
"aarch64-linux" = "sha256-OAFpkTdu+4sag0iIAKlYlpSm53p6kgxeZUd4xodTx3Y="
"x86_64-linux" = "sha256-aWE18OzK96QHAWiEUUaDP6T8k6YZH+Amp1F69NLhT+w="
