[codex]
version = "0.91.0"

[codex.hashes]
"aarch64-darwin" = "sha256-sWBtHwQ9bIfMkyblnSazE1PNgk0vp+n0ZeTxL69HWxg="
"x86_64-darwin" = "sha256-sSr+bsL/AFiV46szHGfsr9P9D8N00GmL1WmPukK32Xc="
"aarch64-linux" = "sha256-fFs0qQdMreYar1EBSgln1MY5cvpnoRvWhN70YFd9gfg="
"x86_64-linux" = "sha256-xzPdhQbdANDsNvMjCN2QK65D6pNTYv18STPBWvTTxkE="

["claude-code"]
version = "2.1.19"
hash = "sha256-K2fJf1eRAyqmtAvKBzpAtMohQ4B1icwC9yf5zEf52C8="
npmDepsHash = "sha256-C8HVKSz1ZQmYNMoLUKk2XUpf5y+Np4nTacCGMVEqO8c="
